# Generated by Django 3.0.2 on 2020-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemanagerpage',
            name='storyline',
            field=models.CharField(max_length=254),
        ),
    ]
